### ISSUE TITLE
a few wanted improvements🙂

### ISSUE THREAD

**Issue by Traction6131** [sys-256/boiurl#3]
Uh elo mise :)
So like my pc doesnt have the battery so we do the gibub issue:

### Ideas to make it bloated:
- darkmode (chad) #1 wait i didnz want to reference that
- make the shortented link to https 
> so like yes if you life in the 20th century you may use http but must dont so like
Just make the link from
http://cockbox.ml/cock to https://cockbox.ml/cock idk how that works but just do it
- set view-point html var thibgsy 
> `<meta name="viewport" content="width=device-width, initial-scale=1.0">` to hab it zoomed in on mobile cause rn it looks pretty shitty ,(on0)

**okay thats all thanks for watching dont forget zo like and subscribe**
And greet flof :> 
Lov u,
barby

**Comment by sys-256** [comment]
lov you too mise i will implement tomorrow or today idk :slightly_smiling_face:

**Comment by Traction6131** [comment]
> lov you too mise i will implement tomorrow or today idk :slightly_smiling_face: 

😃👍🥰

yes implement them as fast as I switched cockbox to boiurl

**Comment by sys-256** [comment]
🧀🧀😱😉😊😇😃😁😄😄

**Comment by sys-256** [comment]
Greetings monsieur, it is my pleasure to contact you again.

I added the viewport thing and a dark mode in 7d775b7. I never coded a dark mode though so create a pr or something if you want to improve it. 😃

Also, I don't really know what you mean by the http->https thing 😸. It should show a https link if you're on https://cockbox.ml and a http link when you're on http://cockbox.ml. For further http to https redirecting you should update your configuration on cockflare or nginx or something :elo:

Kind regards,
your mom

**Comment by Traction6131** [comment]
> 🧀🧀😱😉😊😇😃😁😄😄

oi

**Comment by Traction6131** [comment]
> Greetings monsieur, it is my pleasure to contact you again.
> 
> I added the viewport thing and a dark mode in 7d775b7. I never coded a dark mode though so create a pr or something if you want to improve it. 😃
> 
> Also, I don't really know what you mean by the http->https thing 😸. It should show a https link if you're on https://cockbox.ml and a http link when you're on http://cockbox.ml. For further http to https redirecting you should update your configuration on cockflare or nginx or something :elo:
> 
> Kind regards,
> your mom

bonjour hoi 🗿
very sudo melo and yes I'll check again but I dont use cockflare proxyin but prolly cause its nginx proxied 😉🙂😌

Anyways, very sudo!!!!!!!!!!!!!!!!!!!!!!!
_you'r emom_

**Comment by Traction6131** [comment]
Oh also I wanted to add a cocking compose file but you already did 😌👍

Also im keeping the issue open to assert dominace

**Comment by Traction6131** [comment]
Hm also the halal sauce doesnt update on the cocks even tho new cokcer iamge

**Comment by sys-256** [comment]
> Hm also the halal sauce doesnt update on the cocks even tho new cokcer iamge

Oi sir try `cocker pull sys256/boiurl:latest` and recreate the cocker container :slight_sudo:

> Also im keeping the issue open to assert dominace

😡😡😡😡😡

**Comment by Traction6131** [comment]
> > Hm also the halal sauce doesnt update on the cocks even tho new cokcer iamge
> 
> Oi sir try `cocker pull sys256/boiurl:latest` and recreate the cocker container :slight_sudo:

yes ☺️😊😄🗿

> > Also im keeping the issue open to assert dominace
> 
> 😡😡😡😡😡

_uhem_

HAHHAHAHAHAHAHA 
L BOZO RATIO

**Comment by Traction6131** [comment]
[`sudo`](https://cockbox.ml/)
 ### _**no ad!!!!! 🦥🐋🦷🗣**_
